### ISSUE TITLE
feature request: binary BWT

### ISSUE THREAD

**Issue by arsserpentarium** [IlyaGrebnov/libsais#14]
Hello. I'm grateful for your library. 
However, I would really appreciate if you would add function to perform BWT over binary strings with 1/0 alphabet. Sometimes it's important for entropy analysis. But it require a lot of memory and computation time. Possibly, algorithm could be optimized for such case.

**Comment by IlyaGrebnov** [comment]
Unfortunately, the SAIS algorithm is not suitable for this particular case. Memory usage, which is driven by the constitution of the suffix array and BWT is essentially a byproduct of the suffix array construction. There are algorithms that can construct the BWT directly without using the suffix array, they tend to be slower than the SAIS algorithm.
