### ISSUE TITLE
segmentation fault when building the suffix array for some large texts

### ISSUE THREAD

**Issue by LukasNalbach** [IlyaGrebnov/libsais#15]
With some large texts I get a segmentation fault in libsais64 and libsais64_omp (see ![Screenshot 2023-04-13 100612](https://user-images.githubusercontent.com/82460474/231696127-4dcc90a3-91c4-4e2b-bd47-ff319bfb253f.png)). Here is one of the texts the issue occurs with: https://drive.google.com/file/d/1UJLAHUW9KZVrW7Y8zekAJLnVp6Au_epc/view?usp=sharing. I prepared an example repository "test_libsais" on my github to test this. I can confirm that the issue occurs on Ubuntu 20.04 in WSL2 (with i7-12700K and i7-1160G7) and on Ubuntu 18.04 (with 2x AMD EPYC 7452). I tested with GCC 9.4.0 and 11.1.0 and libomp-dev (5.0.1-1).

**Comment by IlyaGrebnov** [comment]
Hi @LukasNalbach, thank you for taking the time to submit this bug report. It certainly does sound like an issue with libsais64. I will spend some time next week to investigate and hopefully fix the issue.

**Comment by IlyaGrebnov** [comment]
Hi @LukasNalbach I was able to identify and fix the issue in latest version (2.7.2).
