### ISSUE TITLE
Makefile missing

### ISSUE THREAD

**Issue by alebcay** [IlyaGrebnov/libsais#16]
Hello, it looks like the `Makefile` was deleted in 3847654b17a3123a084f3a3dea375e00355846a8. Is this intentional? Is there a new preferred way to build this library now? Thanks.

**Comment by IlyaGrebnov** [comment]
Yes, this is intentional. My intent is to make the library available as source code, and I'm not using this makefile since my main development environment is Windows-based.

**Comment by IlyaGrebnov** [comment]
@alebcay I added CMake file to build library to make it cross platform and verified with MSVC and WSL2.

**Comment by alebcay** [comment]
Awesome, appreciate it. Thanks for the change.
