### ISSUE TITLE
Is SA-IS means using induce sort for suffix array? yuta mori has Open source code of SA-IS

### ISSUE THREAD

**Issue by Daisy-gj** [IlyaGrebnov/libsais#2]
yuta mori's code:https://github.com/y-256/libdivsufsort/ , I've  test his code, the biggest disadvantages is 5 times in-memory usage.

**Comment by IlyaGrebnov** [comment]
Yes, libsais is based on induced sorting [SA-IS](https://www.google.com/search?q=SA-IS+Suffix+Array+Construction+Algorithm) algorithm. Yuta Mori implementation for this algorithm could be found [here ](https://sites.google.com/site/yuta256/sais).

Note, [libdivsufsort](https://github.com/y-256/libdivsufsort/) you quoted above is not based on SA-IS algorithm. You could find description of algorithm [here](https://arxiv.org/pdf/1710.01896.pdf) and it only need O(1) bytes of additional memory (256KB to be exact) which is optimal for this class of algorithms which do not use external memory.

**Comment by Daisy-gj** [comment]
> Yes, libsais is based on induced sorting [SA-IS](https://www.google.com/search?q=SA-IS+Suffix+Array+Construction+Algorithm) algorithm. Yuta Mori implementation for this algorithm could be found [here ](https://sites.google.com/site/yuta256/sais).
> 
> Note, [libdivsufsort](https://github.com/y-256/libdivsufsort/) you quoted above is not based on SA-IS algorithm. You could find description of algorithm [here](https://arxiv.org/pdf/1710.01896.pdf) and it only need O(1) bytes of additional memory (256KB to be exact) which is optimal for this class of algorithms which do not use external memory.

Thanks! I will read this paper.
