### ISSUE TITLE
Constructing the suffix array of a string set

### ISSUE THREAD

**Issue by lh3** [IlyaGrebnov/libsais#23]
Thanks for the library. Very fast!

I would like to build the SA of a set of strings. There are [several ways](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btae333/7681884) to define the SA of a string set. The most common is as follows. Let $`\mathcal{T}=\{T_1,T_2,\ldots,T_n\}`$ be a set of strings over $\Sigma$. Their concatenation is $`T=T_1\$_1T_2\$_2\cdots T_n\$_n`$ where $`\$_1<\$_2<\cdots<\$_n`$ are smaller than all symbols in $\Sigma$. The SA of string set $`\mathcal{T}`$ is defined as the SA of string $T$. This way, you can easily retrieve the $i$-th sequence via LF-mapping.

With libsasi, which supports integer alphabets, we can convert $T$ to an integer array $X$:
```math
X[k]=\left\{\begin{array}{ll}
i & \mbox{if $T[k]=\$_i$} \\
T[k]+n & \mbox{otherwise}
\end{array}\right.
```
It is easy to see the SA of $X$ is identical to the SA of $T$. A problem with the solution is that we need to convert a 8-bit string to a 64-bit integer array. We need 16 bytes per symbol instead of 9 (1-byte symbol plus 8-byte SA).

I modified a 2008 version of Yuta Mori's sais such that during symbol comparisons, we use a special rule to compare sentinels. Briefly, during symbol comparisons, we implicitly replace a sentinel $`\$_i`$ with $`j-|T|`$ where $j$ is the offset of $`\$_i`$ in $T$. This works well. You can find the source code [in this repo](https://github.com/lh3/mssa-bench/). **I wonder if it is easy to implement a similar strategy in libsais.**

Most huge datasets (the one I am working with has 600 billion symbols) logically consist of multiple strings, not a single string. It would be great if we could have a fast and lightweight SA construction algorithm for string sets. Nevertheless, I understand this is not your priority and I suspect it may be technically challenging to apply my old strategy to libsais. Please feel to say "no". Thanks for reading the long and complex request anyway.

**Comment by IlyaGrebnov** [comment]
Ultimately, it is possible to achieve what you want, but it would require a significant amount of work. We would need to copy and surgically modify 10,000 lines of code in order to do so. I believe that the most simpler way to do this would be to start with 10 bytes per symbol, which would only be feasible if the number of strings are less than 64K - 256. If this is the case, we could use libsais16 as a starting point and then expand it to a string of more than 2GB in size.

**Comment by lh3** [comment]
Thanks for the explanation.

**Comment by IlyaGrebnov** [comment]
@lh3 please let me know if approach using libsais16 could work for you I can expand it to large inputs.

**Comment by lh3** [comment]
For my specific application, I am working with a few thousand long strings in one batch, so 16-bit alphabet works. If you can expand libsais16 for strings longer than 2GB, it will work for me. Thanks!

**Comment by IlyaGrebnov** [comment]
Hi @lh3, I have implemented suffix array construction for a long 16-bit array in the latest version (libsais16x64). The only aspect I didn't account for is that the parallelization complexity is quadratic relative to the alphabet size. So this approach works well for a 1-byte alphabet and might not be effective for a 2-byte alphabet. But please give it a try!

**Comment by IlyaGrebnov** [comment]
@lh3 I was able to improve parallelization for 2-byte alphabet, please give it a try!

**Comment by lh3** [comment]
It is working! See the two "-t8c" in the table towards the end of [this README](https://github.com/lh3/mssa-bench/). libsais16x64 seems faster than libsais64 while using less memory. This will help a lot. Thanks!

**Comment by IlyaGrebnov** [comment]
@lh3 I noticed that you called out some multi-threading inconsistencies. I observed the same on non-heterogeneous CPUs (NUMA, chiplets, E/P cores). In that situation clang and corresponding Clang OpenMP runtime performed better. Other option is to change OMP_PROC_BIND and OMP_PLACES runtime variables to change thread binding.

**Comment by IlyaGrebnov** [comment]
@lh3 Heng, thank you for your great work on [msais-lite](https://github.com/lh3/msais-lite). After reviewing your code I was able to implement a similar approach in libsais. As a result, libsais can now build a generalized suffix array (GSA) with 5–9 bytes per symbol (1 byte for the symbol plus 4–8 bytes for the suffix array).

**Comment by attractivechaos** [comment]
Just let you know that I am now using the new gsa algorithm in a [toy benchmark](https://github.com/lh3/mssa-bench). The new `libsais64_gsa()` is ~3% faster than `libsais16x64()` with the old trick. Numbers in that README hasn't been updated yet. I will use the gsa algorithm in my other projects.

**Comment by lh3** [comment]
Just let you know that I am now using the new gsa algorithm in a [toy benchmark](https://github.com/lh3/mssa-bench). The new `libsais64_gsa()` is ~3% faster than the old `libsais16x64()` with the old trick. The numbers in that README hasn't been updated yet. I will use the gsa algorithm in my other projects.
