### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by wupengcheng6819** [IlyaGrebnov/libsais#9]
When dealing with large files, for space reasons I often need a **partial** suffix array, that is, the suffix array of every other (or every n-th) positions of the file. I am guessing it would be much faster than sorting the whole file. Would this be a sensible feature or it would require a considerate amount of work?

**Comment by IlyaGrebnov** [comment]
The libsais library is based on induced sorting SAIS algorithm. Unfortunately this algorithm could not support partial suffix array construction. Some other algorithms (like DC3) might be able to support it, but this is outside of scope for the libsais library.
